version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_URI: mongodb://mongo:27017/myapp
    depends_on:
      - mongo

volumes:
  mongodb-data:
